@echo off
echo Running ESLint...
call npx eslint . > lint-out.txt 2>&1
echo Running TSC...
call npx tsc --noEmit > tsc-out.txt 2>&1
echo Running Prisma Validate...
call npx prisma validate > prisma-out.txt 2>&1
echo Running Build...
call npm run build > build-out.txt 2>&1
echo ALL DONE > all-done.txt
